# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cvasseng/PersonalGit/ThursUI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cvasseng/PersonalGit/ThursUI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.4.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.4.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cvasseng/PersonalGit/ThursUI/CMakeFiles /Users/cvasseng/PersonalGit/ThursUI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cvasseng/PersonalGit/ThursUI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named thursui

# Build rule for target.
thursui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thursui
.PHONY : thursui

# fast build rule for target.
thursui/fast:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/build
.PHONY : thursui/fast

src/controls/thurs.control.button.o: src/controls/thurs.control.button.cpp.o

.PHONY : src/controls/thurs.control.button.o

# target to build an object file
src/controls/thurs.control.button.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.button.cpp.o
.PHONY : src/controls/thurs.control.button.cpp.o

src/controls/thurs.control.button.i: src/controls/thurs.control.button.cpp.i

.PHONY : src/controls/thurs.control.button.i

# target to preprocess a source file
src/controls/thurs.control.button.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.button.cpp.i
.PHONY : src/controls/thurs.control.button.cpp.i

src/controls/thurs.control.button.s: src/controls/thurs.control.button.cpp.s

.PHONY : src/controls/thurs.control.button.s

# target to generate assembly for a file
src/controls/thurs.control.button.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.button.cpp.s
.PHONY : src/controls/thurs.control.button.cpp.s

src/controls/thurs.control.checkbox.o: src/controls/thurs.control.checkbox.cpp.o

.PHONY : src/controls/thurs.control.checkbox.o

# target to build an object file
src/controls/thurs.control.checkbox.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.checkbox.cpp.o
.PHONY : src/controls/thurs.control.checkbox.cpp.o

src/controls/thurs.control.checkbox.i: src/controls/thurs.control.checkbox.cpp.i

.PHONY : src/controls/thurs.control.checkbox.i

# target to preprocess a source file
src/controls/thurs.control.checkbox.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.checkbox.cpp.i
.PHONY : src/controls/thurs.control.checkbox.cpp.i

src/controls/thurs.control.checkbox.s: src/controls/thurs.control.checkbox.cpp.s

.PHONY : src/controls/thurs.control.checkbox.s

# target to generate assembly for a file
src/controls/thurs.control.checkbox.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.checkbox.cpp.s
.PHONY : src/controls/thurs.control.checkbox.cpp.s

src/controls/thurs.control.dropdown.o: src/controls/thurs.control.dropdown.cpp.o

.PHONY : src/controls/thurs.control.dropdown.o

# target to build an object file
src/controls/thurs.control.dropdown.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.dropdown.cpp.o
.PHONY : src/controls/thurs.control.dropdown.cpp.o

src/controls/thurs.control.dropdown.i: src/controls/thurs.control.dropdown.cpp.i

.PHONY : src/controls/thurs.control.dropdown.i

# target to preprocess a source file
src/controls/thurs.control.dropdown.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.dropdown.cpp.i
.PHONY : src/controls/thurs.control.dropdown.cpp.i

src/controls/thurs.control.dropdown.s: src/controls/thurs.control.dropdown.cpp.s

.PHONY : src/controls/thurs.control.dropdown.s

# target to generate assembly for a file
src/controls/thurs.control.dropdown.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.dropdown.cpp.s
.PHONY : src/controls/thurs.control.dropdown.cpp.s

src/controls/thurs.control.editbox.o: src/controls/thurs.control.editbox.cpp.o

.PHONY : src/controls/thurs.control.editbox.o

# target to build an object file
src/controls/thurs.control.editbox.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.editbox.cpp.o
.PHONY : src/controls/thurs.control.editbox.cpp.o

src/controls/thurs.control.editbox.i: src/controls/thurs.control.editbox.cpp.i

.PHONY : src/controls/thurs.control.editbox.i

# target to preprocess a source file
src/controls/thurs.control.editbox.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.editbox.cpp.i
.PHONY : src/controls/thurs.control.editbox.cpp.i

src/controls/thurs.control.editbox.s: src/controls/thurs.control.editbox.cpp.s

.PHONY : src/controls/thurs.control.editbox.s

# target to generate assembly for a file
src/controls/thurs.control.editbox.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.editbox.cpp.s
.PHONY : src/controls/thurs.control.editbox.cpp.s

src/controls/thurs.control.imagegrid.o: src/controls/thurs.control.imagegrid.cpp.o

.PHONY : src/controls/thurs.control.imagegrid.o

# target to build an object file
src/controls/thurs.control.imagegrid.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.imagegrid.cpp.o
.PHONY : src/controls/thurs.control.imagegrid.cpp.o

src/controls/thurs.control.imagegrid.i: src/controls/thurs.control.imagegrid.cpp.i

.PHONY : src/controls/thurs.control.imagegrid.i

# target to preprocess a source file
src/controls/thurs.control.imagegrid.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.imagegrid.cpp.i
.PHONY : src/controls/thurs.control.imagegrid.cpp.i

src/controls/thurs.control.imagegrid.s: src/controls/thurs.control.imagegrid.cpp.s

.PHONY : src/controls/thurs.control.imagegrid.s

# target to generate assembly for a file
src/controls/thurs.control.imagegrid.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.imagegrid.cpp.s
.PHONY : src/controls/thurs.control.imagegrid.cpp.s

src/controls/thurs.control.label.o: src/controls/thurs.control.label.cpp.o

.PHONY : src/controls/thurs.control.label.o

# target to build an object file
src/controls/thurs.control.label.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.label.cpp.o
.PHONY : src/controls/thurs.control.label.cpp.o

src/controls/thurs.control.label.i: src/controls/thurs.control.label.cpp.i

.PHONY : src/controls/thurs.control.label.i

# target to preprocess a source file
src/controls/thurs.control.label.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.label.cpp.i
.PHONY : src/controls/thurs.control.label.cpp.i

src/controls/thurs.control.label.s: src/controls/thurs.control.label.cpp.s

.PHONY : src/controls/thurs.control.label.s

# target to generate assembly for a file
src/controls/thurs.control.label.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.label.cpp.s
.PHONY : src/controls/thurs.control.label.cpp.s

src/controls/thurs.control.listbox.o: src/controls/thurs.control.listbox.cpp.o

.PHONY : src/controls/thurs.control.listbox.o

# target to build an object file
src/controls/thurs.control.listbox.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.listbox.cpp.o
.PHONY : src/controls/thurs.control.listbox.cpp.o

src/controls/thurs.control.listbox.i: src/controls/thurs.control.listbox.cpp.i

.PHONY : src/controls/thurs.control.listbox.i

# target to preprocess a source file
src/controls/thurs.control.listbox.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.listbox.cpp.i
.PHONY : src/controls/thurs.control.listbox.cpp.i

src/controls/thurs.control.listbox.s: src/controls/thurs.control.listbox.cpp.s

.PHONY : src/controls/thurs.control.listbox.s

# target to generate assembly for a file
src/controls/thurs.control.listbox.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.listbox.cpp.s
.PHONY : src/controls/thurs.control.listbox.cpp.s

src/controls/thurs.control.mltext.o: src/controls/thurs.control.mltext.cpp.o

.PHONY : src/controls/thurs.control.mltext.o

# target to build an object file
src/controls/thurs.control.mltext.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.mltext.cpp.o
.PHONY : src/controls/thurs.control.mltext.cpp.o

src/controls/thurs.control.mltext.i: src/controls/thurs.control.mltext.cpp.i

.PHONY : src/controls/thurs.control.mltext.i

# target to preprocess a source file
src/controls/thurs.control.mltext.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.mltext.cpp.i
.PHONY : src/controls/thurs.control.mltext.cpp.i

src/controls/thurs.control.mltext.s: src/controls/thurs.control.mltext.cpp.s

.PHONY : src/controls/thurs.control.mltext.s

# target to generate assembly for a file
src/controls/thurs.control.mltext.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.mltext.cpp.s
.PHONY : src/controls/thurs.control.mltext.cpp.s

src/controls/thurs.control.progressbar.o: src/controls/thurs.control.progressbar.cpp.o

.PHONY : src/controls/thurs.control.progressbar.o

# target to build an object file
src/controls/thurs.control.progressbar.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.progressbar.cpp.o
.PHONY : src/controls/thurs.control.progressbar.cpp.o

src/controls/thurs.control.progressbar.i: src/controls/thurs.control.progressbar.cpp.i

.PHONY : src/controls/thurs.control.progressbar.i

# target to preprocess a source file
src/controls/thurs.control.progressbar.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.progressbar.cpp.i
.PHONY : src/controls/thurs.control.progressbar.cpp.i

src/controls/thurs.control.progressbar.s: src/controls/thurs.control.progressbar.cpp.s

.PHONY : src/controls/thurs.control.progressbar.s

# target to generate assembly for a file
src/controls/thurs.control.progressbar.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.progressbar.cpp.s
.PHONY : src/controls/thurs.control.progressbar.cpp.s

src/controls/thurs.control.rectangle.o: src/controls/thurs.control.rectangle.cpp.o

.PHONY : src/controls/thurs.control.rectangle.o

# target to build an object file
src/controls/thurs.control.rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.rectangle.cpp.o
.PHONY : src/controls/thurs.control.rectangle.cpp.o

src/controls/thurs.control.rectangle.i: src/controls/thurs.control.rectangle.cpp.i

.PHONY : src/controls/thurs.control.rectangle.i

# target to preprocess a source file
src/controls/thurs.control.rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.rectangle.cpp.i
.PHONY : src/controls/thurs.control.rectangle.cpp.i

src/controls/thurs.control.rectangle.s: src/controls/thurs.control.rectangle.cpp.s

.PHONY : src/controls/thurs.control.rectangle.s

# target to generate assembly for a file
src/controls/thurs.control.rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.rectangle.cpp.s
.PHONY : src/controls/thurs.control.rectangle.cpp.s

src/controls/thurs.control.skillbar.o: src/controls/thurs.control.skillbar.cpp.o

.PHONY : src/controls/thurs.control.skillbar.o

# target to build an object file
src/controls/thurs.control.skillbar.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.skillbar.cpp.o
.PHONY : src/controls/thurs.control.skillbar.cpp.o

src/controls/thurs.control.skillbar.i: src/controls/thurs.control.skillbar.cpp.i

.PHONY : src/controls/thurs.control.skillbar.i

# target to preprocess a source file
src/controls/thurs.control.skillbar.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.skillbar.cpp.i
.PHONY : src/controls/thurs.control.skillbar.cpp.i

src/controls/thurs.control.skillbar.s: src/controls/thurs.control.skillbar.cpp.s

.PHONY : src/controls/thurs.control.skillbar.s

# target to generate assembly for a file
src/controls/thurs.control.skillbar.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.skillbar.cpp.s
.PHONY : src/controls/thurs.control.skillbar.cpp.s

src/controls/thurs.control.slider.o: src/controls/thurs.control.slider.cpp.o

.PHONY : src/controls/thurs.control.slider.o

# target to build an object file
src/controls/thurs.control.slider.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.slider.cpp.o
.PHONY : src/controls/thurs.control.slider.cpp.o

src/controls/thurs.control.slider.i: src/controls/thurs.control.slider.cpp.i

.PHONY : src/controls/thurs.control.slider.i

# target to preprocess a source file
src/controls/thurs.control.slider.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.slider.cpp.i
.PHONY : src/controls/thurs.control.slider.cpp.i

src/controls/thurs.control.slider.s: src/controls/thurs.control.slider.cpp.s

.PHONY : src/controls/thurs.control.slider.s

# target to generate assembly for a file
src/controls/thurs.control.slider.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/controls/thurs.control.slider.cpp.s
.PHONY : src/controls/thurs.control.slider.cpp.s

src/thurs.color.o: src/thurs.color.cpp.o

.PHONY : src/thurs.color.o

# target to build an object file
src/thurs.color.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.color.cpp.o
.PHONY : src/thurs.color.cpp.o

src/thurs.color.i: src/thurs.color.cpp.i

.PHONY : src/thurs.color.i

# target to preprocess a source file
src/thurs.color.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.color.cpp.i
.PHONY : src/thurs.color.cpp.i

src/thurs.color.s: src/thurs.color.cpp.s

.PHONY : src/thurs.color.s

# target to generate assembly for a file
src/thurs.color.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.color.cpp.s
.PHONY : src/thurs.color.cpp.s

src/thurs.control.o: src/thurs.control.cpp.o

.PHONY : src/thurs.control.o

# target to build an object file
src/thurs.control.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.control.cpp.o
.PHONY : src/thurs.control.cpp.o

src/thurs.control.i: src/thurs.control.cpp.i

.PHONY : src/thurs.control.i

# target to preprocess a source file
src/thurs.control.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.control.cpp.i
.PHONY : src/thurs.control.cpp.i

src/thurs.control.s: src/thurs.control.cpp.s

.PHONY : src/thurs.control.s

# target to generate assembly for a file
src/thurs.control.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.control.cpp.s
.PHONY : src/thurs.control.cpp.s

src/thurs.input.o: src/thurs.input.cpp.o

.PHONY : src/thurs.input.o

# target to build an object file
src/thurs.input.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.input.cpp.o
.PHONY : src/thurs.input.cpp.o

src/thurs.input.i: src/thurs.input.cpp.i

.PHONY : src/thurs.input.i

# target to preprocess a source file
src/thurs.input.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.input.cpp.i
.PHONY : src/thurs.input.cpp.i

src/thurs.input.s: src/thurs.input.cpp.s

.PHONY : src/thurs.input.s

# target to generate assembly for a file
src/thurs.input.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.input.cpp.s
.PHONY : src/thurs.input.cpp.s

src/thurs.os.o: src/thurs.os.cpp.o

.PHONY : src/thurs.os.o

# target to build an object file
src/thurs.os.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.os.cpp.o
.PHONY : src/thurs.os.cpp.o

src/thurs.os.i: src/thurs.os.cpp.i

.PHONY : src/thurs.os.i

# target to preprocess a source file
src/thurs.os.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.os.cpp.i
.PHONY : src/thurs.os.cpp.i

src/thurs.os.s: src/thurs.os.cpp.s

.PHONY : src/thurs.os.s

# target to generate assembly for a file
src/thurs.os.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.os.cpp.s
.PHONY : src/thurs.os.cpp.s

src/thurs.property.o: src/thurs.property.cpp.o

.PHONY : src/thurs.property.o

# target to build an object file
src/thurs.property.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.property.cpp.o
.PHONY : src/thurs.property.cpp.o

src/thurs.property.i: src/thurs.property.cpp.i

.PHONY : src/thurs.property.i

# target to preprocess a source file
src/thurs.property.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.property.cpp.i
.PHONY : src/thurs.property.cpp.i

src/thurs.property.s: src/thurs.property.cpp.s

.PHONY : src/thurs.property.s

# target to generate assembly for a file
src/thurs.property.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.property.cpp.s
.PHONY : src/thurs.property.cpp.s

src/thurs.renderer.o: src/thurs.renderer.cpp.o

.PHONY : src/thurs.renderer.o

# target to build an object file
src/thurs.renderer.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.renderer.cpp.o
.PHONY : src/thurs.renderer.cpp.o

src/thurs.renderer.i: src/thurs.renderer.cpp.i

.PHONY : src/thurs.renderer.i

# target to preprocess a source file
src/thurs.renderer.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.renderer.cpp.i
.PHONY : src/thurs.renderer.cpp.i

src/thurs.renderer.s: src/thurs.renderer.cpp.s

.PHONY : src/thurs.renderer.s

# target to generate assembly for a file
src/thurs.renderer.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.renderer.cpp.s
.PHONY : src/thurs.renderer.cpp.s

src/thurs.scrollbar.o: src/thurs.scrollbar.cpp.o

.PHONY : src/thurs.scrollbar.o

# target to build an object file
src/thurs.scrollbar.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.scrollbar.cpp.o
.PHONY : src/thurs.scrollbar.cpp.o

src/thurs.scrollbar.i: src/thurs.scrollbar.cpp.i

.PHONY : src/thurs.scrollbar.i

# target to preprocess a source file
src/thurs.scrollbar.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.scrollbar.cpp.i
.PHONY : src/thurs.scrollbar.cpp.i

src/thurs.scrollbar.s: src/thurs.scrollbar.cpp.s

.PHONY : src/thurs.scrollbar.s

# target to generate assembly for a file
src/thurs.scrollbar.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.scrollbar.cpp.s
.PHONY : src/thurs.scrollbar.cpp.s

src/thurs.skin.o: src/thurs.skin.cpp.o

.PHONY : src/thurs.skin.o

# target to build an object file
src/thurs.skin.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.skin.cpp.o
.PHONY : src/thurs.skin.cpp.o

src/thurs.skin.i: src/thurs.skin.cpp.i

.PHONY : src/thurs.skin.i

# target to preprocess a source file
src/thurs.skin.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.skin.cpp.i
.PHONY : src/thurs.skin.cpp.i

src/thurs.skin.s: src/thurs.skin.cpp.s

.PHONY : src/thurs.skin.s

# target to generate assembly for a file
src/thurs.skin.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.skin.cpp.s
.PHONY : src/thurs.skin.cpp.s

src/thurs.surface.o: src/thurs.surface.cpp.o

.PHONY : src/thurs.surface.o

# target to build an object file
src/thurs.surface.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.surface.cpp.o
.PHONY : src/thurs.surface.cpp.o

src/thurs.surface.i: src/thurs.surface.cpp.i

.PHONY : src/thurs.surface.i

# target to preprocess a source file
src/thurs.surface.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.surface.cpp.i
.PHONY : src/thurs.surface.cpp.i

src/thurs.surface.s: src/thurs.surface.cpp.s

.PHONY : src/thurs.surface.s

# target to generate assembly for a file
src/thurs.surface.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.surface.cpp.s
.PHONY : src/thurs.surface.cpp.s

src/thurs.window.o: src/thurs.window.cpp.o

.PHONY : src/thurs.window.o

# target to build an object file
src/thurs.window.cpp.o:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.window.cpp.o
.PHONY : src/thurs.window.cpp.o

src/thurs.window.i: src/thurs.window.cpp.i

.PHONY : src/thurs.window.i

# target to preprocess a source file
src/thurs.window.cpp.i:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.window.cpp.i
.PHONY : src/thurs.window.cpp.i

src/thurs.window.s: src/thurs.window.cpp.s

.PHONY : src/thurs.window.s

# target to generate assembly for a file
src/thurs.window.cpp.s:
	$(MAKE) -f CMakeFiles/thursui.dir/build.make CMakeFiles/thursui.dir/src/thurs.window.cpp.s
.PHONY : src/thurs.window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... thursui"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... src/controls/thurs.control.button.o"
	@echo "... src/controls/thurs.control.button.i"
	@echo "... src/controls/thurs.control.button.s"
	@echo "... src/controls/thurs.control.checkbox.o"
	@echo "... src/controls/thurs.control.checkbox.i"
	@echo "... src/controls/thurs.control.checkbox.s"
	@echo "... src/controls/thurs.control.dropdown.o"
	@echo "... src/controls/thurs.control.dropdown.i"
	@echo "... src/controls/thurs.control.dropdown.s"
	@echo "... src/controls/thurs.control.editbox.o"
	@echo "... src/controls/thurs.control.editbox.i"
	@echo "... src/controls/thurs.control.editbox.s"
	@echo "... src/controls/thurs.control.imagegrid.o"
	@echo "... src/controls/thurs.control.imagegrid.i"
	@echo "... src/controls/thurs.control.imagegrid.s"
	@echo "... src/controls/thurs.control.label.o"
	@echo "... src/controls/thurs.control.label.i"
	@echo "... src/controls/thurs.control.label.s"
	@echo "... src/controls/thurs.control.listbox.o"
	@echo "... src/controls/thurs.control.listbox.i"
	@echo "... src/controls/thurs.control.listbox.s"
	@echo "... src/controls/thurs.control.mltext.o"
	@echo "... src/controls/thurs.control.mltext.i"
	@echo "... src/controls/thurs.control.mltext.s"
	@echo "... src/controls/thurs.control.progressbar.o"
	@echo "... src/controls/thurs.control.progressbar.i"
	@echo "... src/controls/thurs.control.progressbar.s"
	@echo "... src/controls/thurs.control.rectangle.o"
	@echo "... src/controls/thurs.control.rectangle.i"
	@echo "... src/controls/thurs.control.rectangle.s"
	@echo "... src/controls/thurs.control.skillbar.o"
	@echo "... src/controls/thurs.control.skillbar.i"
	@echo "... src/controls/thurs.control.skillbar.s"
	@echo "... src/controls/thurs.control.slider.o"
	@echo "... src/controls/thurs.control.slider.i"
	@echo "... src/controls/thurs.control.slider.s"
	@echo "... src/thurs.color.o"
	@echo "... src/thurs.color.i"
	@echo "... src/thurs.color.s"
	@echo "... src/thurs.control.o"
	@echo "... src/thurs.control.i"
	@echo "... src/thurs.control.s"
	@echo "... src/thurs.input.o"
	@echo "... src/thurs.input.i"
	@echo "... src/thurs.input.s"
	@echo "... src/thurs.os.o"
	@echo "... src/thurs.os.i"
	@echo "... src/thurs.os.s"
	@echo "... src/thurs.property.o"
	@echo "... src/thurs.property.i"
	@echo "... src/thurs.property.s"
	@echo "... src/thurs.renderer.o"
	@echo "... src/thurs.renderer.i"
	@echo "... src/thurs.renderer.s"
	@echo "... src/thurs.scrollbar.o"
	@echo "... src/thurs.scrollbar.i"
	@echo "... src/thurs.scrollbar.s"
	@echo "... src/thurs.skin.o"
	@echo "... src/thurs.skin.i"
	@echo "... src/thurs.skin.s"
	@echo "... src/thurs.surface.o"
	@echo "... src/thurs.surface.i"
	@echo "... src/thurs.surface.s"
	@echo "... src/thurs.window.o"
	@echo "... src/thurs.window.i"
	@echo "... src/thurs.window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

